[package]
description = "ndarray utilities"
documentation = "https://docs.rs/ndarray-utils"
edition = "2021"
license = "MIT"
name = "ndarray-utils"
repository = "https://github.com/foonetic/ndarray-utils"
version = "0.1.3"

[dependencies]
ndarray = "0.15"
num-traits = "0.2"
